# Generated by Django 5.0.1 on 2024-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixedbag',
            name='q_ans',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='multiple',
            name='choi',
            field=models.JSONField(default=list),
        ),
    ]
